version: '3'

services:
  app:
    image: nextjs-openshift-demo
    build: .
    ports: 
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
