import Header from '../components/Header'
import Head from 'next/head'

export default function Conclusion () {
    return (
        <div className="h-screen overflow-y-scroll scrollbar-hide">
            <Head>
                <title>Next.js Openshift Demo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className="grid grid-cols-1 md:grid-cols-2 md:max-w-3xl xl:grid-cols-4 xl:max-w-6xl mx-auto gap-4">
                <div className="md:col-span-2 justify-center flex items-center">
                    <h1 className="text-3xl md:text-5xl mt-5 md:mt-10 ml-2 md:ml-0 font-semibold">🚀 Conclusion 🚀</h1>
                </div>
                <div className='col-span-2 lg:col-span-4 bg-[#f5f5f5] rounded-md shadow-md'>
                    <div className='flex items-center justify-between p-10'>
                        <div className='flex-1 space-y-4'>
                            <h2 className='text-2xl font-bold'>Next.js is an awesome JavaScript Framework!</h2>
                            <p className='ml-4 text-lg'>✅ File-based routing + pre-rendering = high performance</p>
                            <p className='ml-4 text-lg'>✅ Powerful tools ready to use out of the box</p>
                            <p className='ml-4 text-lg'>✅ Developer friendly</p>
                            <p className='ml-4 text-lg'>✅ Supports popular OAuth providers</p>
                            <p className='ml-4 text-lg'>✅ Deploy to OpenShift within minutes!</p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}